### ISSUE TITLE
The parsing results should be oblivious to whitespace

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#1]
Currently, the parsing process is aware of white characters and therefore it is a bit brittle. It is possible to completely ignore all white characters and only focus on the actual parsing:
https://github.com/Beluga-lang/McLTT/blob/5e5a82d1c50a53432883468e9012c1000df18f01/lib/lexer.mll#L16
https://github.com/Beluga-lang/McLTT/blob/5e5a82d1c50a53432883468e9012c1000df18f01/lib/parser.mly#L28

The way to work around white characters is to avoid generating tokens for them at all. I think this can be fixed by replacing the line from `lexer.mll` above with the following:
```
[' ' '\t' '\n' ] { read lexbuf }
```
here `lexbuf` is a special variable implicitly passed by ocamllex to the generated ocaml code. For details, read [^1].

Also change parser accordingly, c.f. [^2][^3].

[^1]: https://v2.ocaml.org/manual/lexyacc.html
[^2]: https://dev.realworldocaml.org/parsing-with-ocamllex-and-menhir.html
[^3]: http://gallium.inria.fr/~fpottier/menhir/manual.html

**Comment by jinh0** [comment]
Yup! I just fixed it in commit 58d5d40ea0b0bd21c15b6be3a84686c7973e9536 .

I had misunderstood how the parser worked. I thought if we didn't specifically ask for a space, something like `funx.x` would be allowed (some weird "keyword" funx). But after adding the changes you indicated, it didn't accept that. Weird.

**Comment by HuStmpHrrr** [comment]
`funx` is parsed as a single token so there won't be any parsing rule to apply.
