### ISSUE TITLE
Fix OCaml and Coq versions

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#10]
We should use the same OCaml and Coq version.

What are yours? @jinh0  @IanGrenville

**Comment by HuStmpHrrr** [comment]
Equations is going to be a necessary library so we should pick a Coq version according to https://coq.inria.fr/opam/released/packages/coq-equations/

it seems it is available from Coq 8.13-8.16. 

If we use Coq 8.16, then our OCaml version should be at least 4.09.0: https://opam.ocaml.org/packages/coq/coq.8.16.0/

**Comment by jinh0** [comment]
I'm on OCaml 4.14.0 and Coq 8.16.1.

**Comment by HuStmpHrrr** [comment]
> I'm on OCaml 4.14.0 and Coq 8.16.1.

could you try to install Equations? if you can, I think 8.16 is the max we can go

**Comment by jinh0** [comment]
Works for me, I was able to install it and use it on some sample code:

```coq
From Equations Require Import Equations.

Inductive bool : Set := true : bool | false : bool.

Equations neg (b: bool) : bool :=
  neg true := false;
  neg false := true.

```

**Comment by HuStmpHrrr** [comment]
I think we can fix the OCaml and Coq versions. They are explicitly recorded in the README file.
