### ISSUE TITLE
Add subtyping for cumulativity

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McLTT#121]
C.f. #120

Let's implement subtyping

- [x] syntactic extension
    - #122
    - #127
- [x] PER model
    - ~~#125~~
    - #128
- [x] PER model lemma
    - #128
- [x] completeness
    - #130 
    - #133
- [x] soundness
    - #140 
    - #153
- [x] subtyping checker
    - #124
    - #152

**Comment by Ailrun** [comment]
@HuStmpHrrr It seems like Meven knows some :)
https://coq.discourse.group/t/coqs-cumulativity/2334

**Comment by Ailrun** [comment]
Oh lol that's actually an answer on your email haha

**Comment by HuStmpHrrr** [comment]
I think contra-variant subtyping will have to be abandoned (#125 ), as per our offline discussions. Too many things just can't work out. I will prepare a PR to do only co-variant subtyping.

see

![IMG20240625174707](https://github.com/Beluga-lang/McLTT/assets/6101711/92b50193-9693-4ce3-be8e-426fa11be050)

**Comment by Ailrun** [comment]
I will leave this issue open for the contravariant subtyping.

**Comment by Ailrun** [comment]
Actually there is #129, so let's close this.
