### ISSUE TITLE
Make Gluing Model Unary

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McLTT#131]
C.C. @HuStmpHrrr 

In the gluing model definition of
```coq
Inductive glu_univ_elem_core : glu_typ_pred -> glu_exp_pred -> domain -> domain -> Prop
```
why do we need two `domain` types? In the Agda mechanization, sure, we used `A ≈ B ∈ 𝕌 j` (actually even there, why doesn't `A ∈′ 𝕌 j` work? Our `transport` or other lemmas there are all one-sided after all), but here we repeat the structure of `A ≈ B ∈ 𝕌 j` in the model anyway, and what we need is relating one syntactic term with one domain term.

**Comment by Ailrun** [comment]
I got this question while defining the gluing model for substitutions. Even in the Agda mechanization, we used a one-sided definition for the model instead of a binary one.

**Comment by HuStmpHrrr** [comment]
I think in principle the gluing model is ok to be unary. try to change it to unary. I think it will just work.

**Comment by Ailrun** [comment]
Yeah, I will try.

**Comment by HuStmpHrrr** [comment]
I think that will probably work out better for the subtyping relation. I think you can also try to define subtyping for gluing. it might be a bit twisted.

**Comment by Ailrun** [comment]
#132 resolves this.
