### ISSUE TITLE
Make gluing model works with generalized rewriting

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McLTT#135]
~~They are defined as `binary_relation`, which blocks all `Hint Extern`s in https://github.com/coq/coq/blob/38d6695084c9d38b5af7258a85702a1d01a49dce/theories/Classes/Morphisms.v due to
https://github.com/coq/coq/blob/38d6695084c9d38b5af7258a85702a1d01a49dce/theories/Classes/Morphisms.v#L37-L53
Note that all of these uses `relation`, not `binary_relation`. Once unfolded, they are identical, but Ltac does not know the unfolded structure and typeclass resolution fails.~~

~~Without those typeclasses, it is hard to use the generalized rewriting, which helps a lot when dealing with functionality of the gluing model.~~

It turns out one possible root cause is opaque `arrows`. Generalized rewriting works with `Typeclasses Transparent arrows`.

**Comment by HuStmpHrrr** [comment]
Is that why you have to pose those instances? A solution is to copy necessary parts in RelationalClasses and give definitions in a workable way. Frankly, this file is stupid.

**Comment by Ailrun** [comment]
No, for completeness, this one is fine since `relation_equivalence` uses `relation`, not `binary_relation`. Those `pose` things are from a different problem.

**Comment by HuStmpHrrr** [comment]
so what problem does this cause?

**Comment by Ailrun** [comment]
General rewriting (or `setoid_rewrite`) does not work at all.

**Comment by Ailrun** [comment]
It works with `Typeclasses Transparent arrows.`

**Comment by HuStmpHrrr** [comment]
let's close it with some PR if there is one, so we can keep track of it.

**Comment by Ailrun** [comment]
I think it would be better to open another. Or at least rename this issue. Let me rename this,
