### ISSUE TITLE
Soundness and Logical Relations

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#136]
@Ailrun Let's split work in this issue. List and pick stuff that you want to work on so we don't overlap.

- [x] subtyping
  - #151
  - #153
  - #157
- [x] cumulativity
  - #150
- [x] realizability
  - #140  
- [ ] typing rules
  - #113 (Roadmap issue)

**Comment by Ailrun** [comment]
I will first fix #135.

**Comment by HuStmpHrrr** [comment]
I will look into realizability. subtyping is gonna be interesting. @Ailrun do you want to handle it? or do you want to swap.

**Comment by Ailrun** [comment]
By subtyping, you mean subtyping cases? I didn't get it when you said subtyping logrel for soundness, as I expected something like
https://gitlab.com/JasonHuZS/practice/-/blob/master/MLTT/Soundness/Terms.agda#L22-26
(that using syntactic judgement) or similar.

**Comment by HuStmpHrrr** [comment]
there should be lemmas for subtyping in the logical relations too. it should quantify what happens to the logical relation when there is a subtyping in the domain.

**Comment by Ailrun** [comment]
You mean something like
```
Lemma glu_univ_elem_typ_subtyping : forall {i a a' P P' El El' Γ A},
    {{ Sub a <: a' at i }} ->
    {{ DG a ∈ glu_univ_elem i ↘ P ↘ El }} ->
    {{ DG a' ∈ glu_univ_elem i ↘ P' ↘ El' }} ->
    P Γ A ->
    exists A', {{ Γ ⊢ A ⊆ A' }} /\ P' Γ A'.
```

**Comment by HuStmpHrrr** [comment]
It should be universal over A', but otherwise I think this should be the theorem. Not sure if there's more.

**Comment by Ailrun** [comment]
How it can be universal in `A'`? I mean, `A'` should be a specific type that corresponds to `a'`, not any supertype of `A`.

**Comment by HuStmpHrrr** [comment]
put `P' Γ A'` in the implication too. you just prove A is a subtype of A'.

**Comment by Ailrun** [comment]
Then what would that provide? For subtyping cases we need if `El G M A m` then `El' G M A' m` for some supertype `A'`

**Comment by HuStmpHrrr** [comment]
this one will also prove the previous lemma as part of it. proving this one should also work.

**Comment by Ailrun** [comment]
It seems like the subtyping lemmas require realizability. In the following lemma,
```
Lemma glu_univ_elem_typ_per_univ_escape : forall {i a a' P P' El El' Γ A A'},
    {{ Dom a ≈ a' ∈ per_univ i }} ->
    {{ DG a ∈ glu_univ_elem i ↘ P ↘ El }} ->
    {{ DG a' ∈ glu_univ_elem i ↘ P' ↘ El' }} ->
    {{ Γ ⊢ A ® P }} ->
    {{ Γ ⊢ A' ® P' }} ->
    {{ Γ ⊢ A ≈ A' : Type@i }}.
```
we need `{{{ Γ, IT ⊢ # 0 : IT[Wk] ® ⇑! A 0 ∈ IEl }}}` in pi case, which probably is derivable after realizability.
