### ISSUE TITLE
No use premise

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#144]
https://github.com/Beluga-lang/McLTT/blob/06389498b20d68b502e3469f8d322abbd0a80ede/theories/Core/Soundness/LogicalRelation/Definitions.v#L306-L309

@Ailrun do you plan on doing anything with this? As it is, it doesn't help anything at all. If you want to remove it or introduce a new substitution, either is fine.

**Comment by Ailrun** [comment]
I will remove it.
