### ISSUE TITLE
Cumulativity should relate input and output relations

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#146]
https://github.com/Beluga-lang/McLTT/blob/86f48d948352683b1c6c28413db5d1d2894c5d0d/theories/Core/Soundness/LogicalRelation/Lemmas.v#L623-L627

P and El should not change. This is how it is in Agda: https://hustmphrrr.github.io/mech-type-theories/MLTT.Soundness.Cumulativity.html

**Comment by HuStmpHrrr** [comment]
ok I see. I am wrong. Indeed, there should be an implication.

**Comment by Ailrun** [comment]
Yeah, reverse direction for `El` should be handled by a lowering lemma. You know, this is why the lowering lemma is (at least in the technical level) so important.

**Comment by HuStmpHrrr** [comment]
yeah I think this lemma can be changed to a form easier to prove though. notice that the existential claim can already be established due to cumulativity of the per model, so what's important is really the implication part. so P' and El' here should also be universally quantified, and the conclusion should be implications.

**Comment by Ailrun** [comment]
Yeah, that would be easier to prove. I will change the form if you are not going to do so in a few days.

**Comment by HuStmpHrrr** [comment]
no I am not. go ahead. I can prove monotonicity

**Comment by HuStmpHrrr** [comment]
cumulativity should probably go under a different file, because it uses realizability.
