### ISSUE TITLE
Can we remove this file?

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#176]
https://github.com/Beluga-lang/McLTT/blob/7bd92e7e842bd3266f378df06efa24e082ad2afc/theories/Core/Syntactic/ExpNoConfusion.v#L1

Now Coq is updated, I suppose this problem is fixed? @Ailrun

**Comment by Ailrun** [comment]
Actually I tried to remove that while update, and unfortunately no, it didn't work. It seems like there were 2 different issues between Equations and Menhir, and only one of them is fixed with Coq 8.20.

**Comment by HuStmpHrrr** [comment]
ok, leave it for now then.

**Comment by Ailrun** [comment]
We don't actually need this file, so removed in 53fff5aeb972ca64adb5e38cf8d64451ecc6e7ba.
