### ISSUE TITLE
Is this function used?

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#177]
https://github.com/Beluga-lang/McLTT/blob/d43ab2ca6edc480a5969aadec8c3a63f45bebdf9/driver/Main.ml#L7

I don't see a place to apply it? @Ailrun

**Comment by Ailrun** [comment]
No, it is a legacy entrypoint, previously used for Test.ml. We can remove that.

**Comment by HuStmpHrrr** [comment]
also how do you run the main function? I don't see any generated binary?

**Comment by Ailrun** [comment]
Oh oops I forgot to update the README.
```
$ dune utop
# open Mcltt.Main
# main ()
```
or
```
# main ~default_fp:"...path to file..." ()
```

**Comment by Ailrun** [comment]
Yeah we need to add something like
https://ocaml.org/manual/4.14/api/Arg.html
but other than that it just about calling that function
