### ISSUE TITLE
Using SVG as the Table of Content?

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McLTT#222]
A script in https://github.com/Beluga-lang/McLTT/tree/pr-generate-dep-svg branch can generate the following svg, and each node is linked to the actual module. This might be visually more useful than plain text TOC.

![dep](https://github.com/user-attachments/assets/4e610043-9698-4fc3-8841-dd451cd5d973)

**Comment by HuStmpHrrr** [comment]
Is it just a pic or it contains hyperlinks? If it's just a pic, let's just embed it in the homepage. it should be quite easy to do by changing the markdown file.

**Comment by HuStmpHrrr** [comment]
ok so it contains links. we could just change the header file: https://github.com/Beluga-lang/McLTT/blob/main/assets/extra/header.html and point readers to this pic in the index by default. If you could centralize it and make the style somewhat agree with the coqdoc that's even better.

**Comment by Ailrun** [comment]
Closed by #225, #226, c4636e14a8dd9533026246b0ef4f0c407527e8d1, b91603056330692615c318d2e0651c63c43c1e47, #227, 577a0cb5d8cbc0a07b9716221bca18754f32c391, 18954058b4660cb5ae3f17e554d9152601ce8cc6, and 091598d038263fbec09ba3d3b2af204630f53f41
