### ISSUE TITLE
Stabilize and release

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#224]
I think we should stabilize the repo and make a release, so that we put a stamp on what is ready. During the process, we will create a tag and this will be handy. If this repo ever needs to evolve in different ways, it is convenient to choose from these tags.

**Comment by HuStmpHrrr** [comment]
I think we are good to go?

**Comment by Ailrun** [comment]
I guess so. We can deal with other changes (such as some syntactic redundancy of `let` binding) later.

**Comment by HuStmpHrrr** [comment]
I've done the release but the release tab is not showing on the right.

**Comment by HuStmpHrrr** [comment]
found it. github is really counterintuitive on this.
