### ISSUE TITLE
optimize presup

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#229]
https://github.com/Beluga-lang/McLTT/blob/ext/prop-eq/theories/Core/Syntactic/Presup.v

**Comment by HuStmpHrrr** [comment]
c.f. #223

**Comment by Ailrun** [comment]
From #223 by myself:
> I realized that we don't even need mutual induction for presupposition of `wf_exp`/`wf_sub`. The "enhanced" rules for subtyping provide immediate (inductive) proof for well-formedness of type of `wf_exp`.

In fact, we can prove type part of presuppositions (for `wf_exp`/`wf_sub`/`wf_exp_eq`/`wf_sub_eq`) separately and use `SystemOpt.v`-like rules in the rest of presuppositions of `wf_*_eq`s.

**Comment by Ailrun** [comment]
Now it takes 35sec.

**Comment by HuStmpHrrr** [comment]
that sounds good. I think we can probably close this issue.
