### ISSUE TITLE
Fix the infix operators of the syntax

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#23]
> Oh sorry I forgot about this, it was conflicting with notation that was in the standard library stuff I was importing and I couldn't find a way to only enable one of them within Elaborator.v
> Would putting the notations in Syntax.v in their own scope fix it?

_Originally posted by @IanGrenville in https://github.com/Beluga-lang/McLTT/pull/12#discussion_r1155385690_
            
It probably would make more sense if we have our own parsing scope: https://coq.inria.fr/refman/user-extensions/syntax-extensions.html

**Comment by Ailrun** [comment]
I guess this one is also kinda done? I will close this for now; if you have any other concerns please feel free to open this again.
