### ISSUE TITLE
Do we have consistency and canonical forms?

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#233]
I can't find the theorems for them.

**Comment by Ailrun** [comment]
For pi type, https://github.com/Beluga-lang/McLTT/blob/main/theories/Core/Semantic/Consequences.v#L48
But for others, I don't think we have one.

**Comment by HuStmpHrrr** [comment]
I suppose we don't have consistency? Is there one?

**Comment by Ailrun** [comment]
Now we have.
