### ISSUE TITLE
redundant comparison in readback and PER

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#252]
https://github.com/Beluga-lang/McLTT/blob/9ed1a85ae63e1f1fb5cbd297af509bce18bd800b/theories/Core/Semantic/Readback/Definitions.v#L23

the inner check on `ℕ` is unnecessary. Since readback is type directed, this inner check necessarily passes because we only pass in well-typed terms for normalization. 

In fact, 

https://github.com/Beluga-lang/McLTT/blob/9ed1a85ae63e1f1fb5cbd297af509bce18bd800b/theories/Core/Semantic/PER/Definitions.v#L69

even here we don't even need to care about `ℕ` because we are relating two values of type Nat, so we can safely just say for all domain types, and we know for sure they are going to be `ℕ`.

**Comment by HuStmpHrrr** [comment]
c.f. my recent change on the Agda side: https://github.com/HuStmpHrrr/mech-type-theories/compare/340b33cf749faecc66a5251c29a7084d0474e0e7...cc846c2b0ef4296582a7850293191aaa945b06cd

**Comment by HuStmpHrrr** [comment]
after some thoughts, I think the type annotation of this uparrow is not even necessary! let's remove it at all. this is a pure gain. make this change before #224

**Comment by Ailrun** [comment]
What do you mean by "the type annotation of this uparrow"? If you mean `⇑ a m` (for some `a`), that should be there to extract neutral `m`.

**Comment by HuStmpHrrr** [comment]
no, it's completely unused in the readback process. whenever you need a type, it's already provided by the down arrow. the information in the up arrow is redundant.

**Comment by Ailrun** [comment]
It is unused, but we need `m : domain_ne`.

**Comment by HuStmpHrrr** [comment]
doesn't mean we need to keep `a`.

**Comment by Ailrun** [comment]
Ah I see you mean we don't need `a` for `⇑ a`, not `⇑` itself. Make sense.

**Comment by Ailrun** [comment]
I think we still need it. https://github.com/Beluga-lang/McLTT/blob/9ed1a85ae63e1f1fb5cbd297af509bce18bd800b/theories/Core/Semantic/Evaluation/Definitions.v#L60-L62
Here, the type for the first uparrow is used to provide the type for the downarrow.

**Comment by HuStmpHrrr** [comment]
ok i see. so eliminations for negative types do require this type information.

then at least we can remove the unnecessary check for the inductively defined types.
