### ISSUE TITLE
helper rules

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#32]
In my agda proof, https://gitlab.com/JasonHuZS/practice/-/blob/master/MLTT/Statics/Full.agda, there are rules that are marked as `remove after presupposition`. Proves these rules as lemmas. They can be added to the hint database.

**Comment by HuStmpHrrr** [comment]
I think this is going to be a low hanging fruit for you. Remember how we had two sets of rules? That was stupid. We should always work with the full set of rules and then add simplified rules as lemmas.

**Comment by Ailrun** [comment]
That would make pattern matching harder, wouldn't it? @HuStmpHrrr

**Comment by HuStmpHrrr** [comment]
How does that impact pattern matching? The full rules need to be written down in any case and they contain strictly more premises than the concise rules, so they can only induce stronger IH.

**Comment by Ailrun** [comment]
Ah, right. I was somewhat mixed Agda and Coq approaches... Ok, this is quite an easy one. BTW, let me put the domain and PER first to make the target clearer.
