### ISSUE TITLE
Iterate Pi and fun's arguments in the parser

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#5]
It should be relatively easy to parse

```
Pi (x : A) (y : B) ... (z : C) . T
```
into 
```
Pi ("x", A, Pi ("y", B, ... T))
```

We can require one or more `(x : A)` after `Pi` to do this.

The same applies for `fun`.

**Comment by jinh0** [comment]
Added in d5625ae0da164a302ab50b596bfabdcdbdda18db .

**Comment by HuStmpHrrr** [comment]
why in reverse? 

you can use `+` suffix for >= 1 repetitions, c.f. http://gallium.inria.fr/~fpottier/menhir/manual.html#fig%3Asugar

**Comment by HuStmpHrrr** [comment]
I suppose reverse because of `fold_right`. you can just parse in the original order and `fold_left` should give you the correct result.

**Comment by jinh0** [comment]
> you can use + suffix for >= 1 repetitions, c.f. http://gallium.inria.fr/~fpottier/menhir/manual.html#fig%3Asugar

Works like a charm! bf7c8bd7a560f1aa1cb4c90daefef9c896bc01ed

I did
```ocaml
args_list:
  l = args_obj+ { List.rev l };

args_obj:
  LPAREN; x = VAR; COLON; t = obj; RPAREN { (x, t) };
```
with the `fold_left`:
```ocaml
  | LAMBDA; args = args_list; DOT; o = obj {
    List.fold_left (fun curr (a, t) -> Cst.Fun (a, t, curr)) o args
  }
```
