### ISSUE TITLE
Why fail 3?

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#73]
https://github.com/Beluga-lang/McLTT/blob/cb4c726c92c668aa89f60167b91a6e7d86feb6b6/theories/Core/Semantic/PER/Lemmas.v#L256

If I am counting correctly, the right level should be 2. Why 3? Larger level will have unexpected effects when used in a larger tactic.

**Comment by Ailrun** [comment]
I don't know, I tried 2 and it didn't work (Like, if I replace `eauto` with `auto`, it doesn't give an error)

**Comment by Ailrun** [comment]
Actually, seeing it again, now I understand. It should be 3. One for `first`, one for `match`, and the other for `repeat`.

**Comment by Ailrun** [comment]
(The point of that error is that error is "critical", i.e. something is wrong in the definition of tactic/previous hints, which would be helpful when we extend the proof with Cocon)

**Comment by HuStmpHrrr** [comment]
ok
