### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by HuStmpHrrr** [Beluga-lang/McLTT#85]
https://github.com/coq-community/docker-coq-action

**Comment by HuStmpHrrr** [comment]
looking at other people's setup. should we also have a opam file too? 

https://github.com/jwiegley/category-theory/blob/master/coq-category-theory.opam

**Comment by Ailrun** [comment]
It seems like, yeah, that action requires an opam file.

**Comment by Ailrun** [comment]
Now CI takes only 2 min! I guess we can close this. Later, I will write some doc for the current CI.

**Comment by HuStmpHrrr** [comment]
great. so we indeed use the docker container.

**Comment by Ailrun** [comment]
Yeah, and use our own docker image uploaded on GitHub package registry.
